### ISSUE TITLE
Exibicao do mes no exercicio proposto 01 Aula Lists

### ISSUE THREAD

**Issue by marqueserick** [cami-la/curso-dio-intro-collections#1]
Na [resolução para o exercicio 01 da aula de Lists](https://github.com/cami-la/curso-dio-intro-collections/blob/master/src/br/com/dio/collection/list/ExercicioProposto01.java) , na linha 32, o mês vai ser informado baseado no index da temperatura na lista de temperaturas. O problema dessa solução é se o usuario inserir o mesmo valor de temperatura em mais de 1 mês, vai retornar somente o primeiro mês com a temperatura indicada.

**Comment by cami-la** [comment]
Hummmm, bem levantada essa questão, Erick. Obrigada pelo feedback. :smile:
Vou resolver novamente consertando esta falha e te notifico. Assim você compara minha solução com a sua, beleza?

**Comment by marqueserick** [comment]
Como combinamos, [minha resolução.](https://github.com/marqueserick/curso-trabalhandoComcollections/blob/main/src/com/erickmarques/metodosList/exerciciosPropostos/Exercicio1.java)

**Comment by cami-la** [comment]
Pronto, @marqueserick. Resolvi novamente!
Desta vez utilizando stream e swich-case. 

Se possível, pega minha resolução e repete o teste para ver se agora está correto.
Caso negativo, tento novamente sem problemas. :smile:
