### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by Brujahhell** [cami-la/curso-dio-intro-collections#10]
Bom dia, estou tentando fazer um sorteador de itens (coisa de rpg rsrsrs)
consegui fazer o Intellij ler o arquivo .txt, ele fez o sorteio e mostrou o numero, porem eu queria que ele mostrasse oq esta escrito naquele numero(naquela linha) e não estou conseguindo fazer isso pois o numero é um int e a leitura necessita de uma String.
poderia me ajudar???

aqui esta o código. 
obs: o arquivo txt que ele esta lendo esta no final do codigo é o itens.txt

package ItensMagicos;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Random;

public class Main {

    public static void main(String[] args) throws IOException {

        int item;

        Path path = Path.of("C:\\Users\\Bruno\\Downloads\\itens.txt");

        Random random = new Random();
        item = random.nextInt(919);

        List<String> strings = Files.readAllLines(path);
        for (String ItensMagicos : strings) {
            System.out.println(ItensMagicos);

        }

            System.out.println("Voce encontrou um item, veja o item " + item);

        }
    }

[itens.txt](https://github.com/cami-la/curso-dio-intro-collections/files/8223549/itens.txt)

**Comment by cami-la** [comment]
> ystem.out.println("Voce encontrou um item, veja o item " + item);

**Comment by Brujahhell** [comment]
Camila, muito obrigado, deu certinho aqui. 
eu só subi o 

"System.out.println("Voce encontrou um item, veja o item " + item);" 

e coloquei ele no 
System.out.println(currentLine);

ficando 
System.out.println("Voce encontrou um item, " + currentLine);

muito obrigado mesmo...
