### ISSUE TITLE
Ordenação de elementos em uma coleção List - parte 2

### ISSUE THREAD

**Issue by NildsonKleyton** [cami-la/curso-dio-intro-collections#11]
Olá!
Muito obrigado pelas aulas até agora, no Bootcamp GFT Start #4 Java

Alterei o ultimo método do ExemploOrdenarList, deixando na ordem por :
nome - idade -  cor
deu certo mas seria assim mesmo?

![image](https://user-images.githubusercontent.com/66071235/159190345-885e75ba-d78c-47a6-838d-d506f477f8a1.png)

![image](https://user-images.githubusercontent.com/66071235/159189993-234599bc-a38f-4751-9f47-9e5f69903983.png)

Grato!!!!

**Comment by cami-la** [comment]
> Olá! Muito obrigado pelas aulas até agora, no Bootcamp GFT Start #4 Java
> 
> Alterei o ultimo método do ExemploOrdenarList, deixando na ordem por : nome - idade - cor deu certo mas seria assim mesmo?
> 
> ![image](https://user-images.githubusercontent.com/66071235/159190345-885e75ba-d78c-47a6-838d-d506f477f8a1.png)
> 
> ![image](https://user-images.githubusercontent.com/66071235/159189993-234599bc-a38f-4751-9f47-9e5f69903983.png)
> 
> Grato!!!!

Isso! Está ordenando!
É importante saber esse conceito, mas no dia a dia geralmente, se usa STREAM API e não fazemos essas comparações "na mão". 
Se você ainda não teminou o curso, no final eu falo um pouco de Stream e faço comparações usando ele. (:

**Comment by NildsonKleyton** [comment]
Ainda não

> > Olá! Muito obrigado pelas aulas até agora, no Bootcamp GFT Start #4 Java
> > Alterei o ultimo método do ExemploOrdenarList, deixando na ordem por : nome - idade - cor deu certo mas seria assim mesmo?
> > ![image](https://user-images.githubusercontent.com/66071235/159190345-885e75ba-d78c-47a6-838d-d506f477f8a1.png)
> > ![image](https://user-images.githubusercontent.com/66071235/159189993-234599bc-a38f-4751-9f47-9e5f69903983.png)
> > Grato!!!!
> 
> Isso! Está ordenando! É importante saber esse conceito, mas no dia a dia geralmente, se usa STREAM API e não fazemos essas comparações "na mão". Se você ainda não teminou o curso, no final eu falo um pouco de Stream e faço comparações usando ele. (:

**Comment by NildsonKleyton** [comment]
Ainda não.

Ok! então irei continua a aulas.
Obrigado
